export enum ErrorCode {
  /******************************
   *           AUTH
   ******************************/
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN = "AUTH_FORBIDDEN",
  AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID",
  AUTH_ACCOUNT_LOCKED = "AUTH_ACCOUNT_LOCKED",

  /******************************
   *           USER
   ******************************/
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_EMAIL_ALREADY_USED = "USER_EMAIL_ALREADY_USED",
  USER_INACTIVE = "USER_INACTIVE",

  /******************************
   *      OTP / VERIFICATION
   ******************************/
  OTP_INVALID = "OTP_INVALID",
  OTP_EXPIRED = "OTP_EXPIRED",
  OTP_EMAIL_NOT_VERIFIED = "OTP_EMAIL_NOT_VERIFIED",
  OTP_MAGIC_LINK_INVALID = "OTP_MAGIC_LINK_INVALID",
  OTP_MAGIC_LINK_EXPIRED = "OTP_MAGIC_LINK_EXPIRED",

  /******************************
   *         VALIDATION
   ******************************/
  VALIDATION_FAILED = "VALIDATION_FAILED",
  VALIDATION_REQUIRED_FIELD = "VALIDATION_REQUIRED_FIELD",
  VALIDATION_INVALID_FORMAT = "VALIDATION_INVALID_FORMAT",
  VALIDATION_TOO_SHORT = "VALIDATION_TOO_SHORT",
  VALIDATION_TOO_LONG = "VALIDATION_TOO_LONG",
  VALIDATION_OUT_OF_RANGE = "VALIDATION_OUT_OF_RANGE",
  VALIDATION_VALUE_NOT_ALLOWED = "VALIDATION_VALUE_NOT_ALLOWED",

  /******************************
   *          RESOURCE
   ******************************/
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RESOURCE_CONFLICT = "RESOURCE_CONFLICT",
  RESOURCE_LOCKED = "RESOURCE_LOCKED",

  /******************************
   *           SYSTEM
   ******************************/
  SYSTEM_INTERNAL_ERROR = "SYSTEM_INTERNAL_ERROR",
  SYSTEM_SERVICE_UNAVAILABLE = "SYSTEM_SERVICE_UNAVAILABLE",
  SYSTEM_TIMEOUT = "SYSTEM_TIMEOUT",
  SYSTEM_UNKNOWN_ERROR = "SYSTEM_UNKNOWN_ERROR",

  /******************************
   *         PERMISSION
   ******************************/
  PERMISSION_DENIED = "PERMISSION_DENIED",
  PERMISSION_ROLE_REQUIRED = "PERMISSION_ROLE_REQUIRED",

  /******************************
   *         THROTTLER
   ******************************/
  THROTTLER_TOO_MANY_REQUESTS = "THROTTLER_TOO_MANY_REQUESTS",
}
