name: "Deploy to Server With SCP"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Confirm Deployment[test]"
        run: echo "Deployment [test] Successfull!"
      